### Register User
POST http://localhost:5000/api/user/register

{
  "username":"person",
  "email":"person@gmail.com",
  "password":"123",
  "phone_number":"",
  "address":"",
  "image_url":""
}

### Login User
POST http://localhost:5000/api/user/login

{
  "email":"person@gmail.com",
  "password":"123"
}

### Logout User
DELETE http://localhost:5000/api/user/logout