### Get Province
GET http://localhost:5000/api/region/province

### Get City By Province Id
GET http://localhost:5000/api/region/city/6

### Register User
POST http://localhost:5000/api/user/register

{
  "username":"person",
  "email":"person@gmail.com",
  "password":"123",
	"city_id":"153",
  "phone_number":"",
  "address":"",
  "image_url":""
}

### Login User
POST http://localhost:5000/api/user/login

{
  "email":"sendi@gmail.com",
  "password":"123"
}

### Get Token
GET http://localhost:5000/api/user/token

### Logout User
DELETE http://localhost:5000/api/user/logout

### Test Middleware
GET http://localhost:5000/api/test/middleware
Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbmR5Iiwic3ViIjoic2FuZHlAZ21haWwuY29tIiwiZXhwIjoxNjk3MjE0MTg0LCJqdGkiOiIzNzcyZDllYS04N2M0LTRlMDEtOGYxNC04NmIyYjViZTVmNjgifQ.RqPvvBTGahRN4Sopd_5dfhpSfAgsg9KKQJ7nP3-uhJY

### Test Middleware Admin
GET http://localhost:5000/api/test/admin
Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbmR5Iiwic3ViIjoic2FuZHlAZ21haWwuY29tIiwiZXhwIjoxNjk3MjE0MjM5LCJqdGkiOiIzNzcyZDllYS04N2M0LTRlMDEtOGYxNC04NmIyYjViZTVmNjgifQ.Ho7nRNa4OeficelCYCkS1qQRS-RtPzrOmV52oiQyD7k

### Update User
PUT http://localhost:5000/api/user/707f5b86-7a34-4888-abf5-f72b23fc30af
Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBlcnNvbiIsInN1YiI6InBlcnNvbkBnbWFpbC5jb20iLCJleHAiOjE2OTcxMzE4NDEsImp0aSI6ImFkZjRiNzk0LWYzOTgtNDY0YS1iNmQ1LWVmOGEwNzhmMDcwNSJ9.xl0DZ8P93lOsg5STTBT9EF0cvYp480ion8tTRYEuxPo

{
  "username":"",
	"email":"person@gmail.com",
	"password":"",
	"city_id":"",
	"phone_number":"",
	"address":"Jl. Buntu",
	"image_url":""
}

### Delete User
DELETE http://localhost:5000/api/user/adf4b794-f398-464a-b6d5-ef8a078f0705
Access-Token:

### Find User
GET http://localhost:5000/api/user/find?page=1&limit=5&search=a
Access-Token:

### Get User
GET http://localhost:5000/api/user/4e9497c1-fb82-4301-94a8-7d0b4d6c4f53
Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbmR5Iiwic3ViIjoic2FuZHlAZ21haWwuY29tIiwiZXhwIjoxNjk3NTE0MDc2LCJqdGkiOiIzNzcyZDllYS04N2M0LTRlMDEtOGYxNC04NmIyYjViZTVmNjgifQ.h4NE77F1qJFeD4VHtGg5LmVI-ROmB46cbQleA_vWvWc

### Create Store
POST http://localhost:5000/api/store/create
Access-Token:

{
  "store_name":"Toko Sembako",
	"description":"contoh deskripsi",
	"category":"rumahan",
	"image_url":""
}

### Update Store
PUT http://localhost:5000/api/store/e9c49a8d-f156-431a-9f65-e3012fb29f45
Access-Token:

{
  "store_name":"Toko Game",
	"description":"contoh deskripsi",
	"category":"hiburan",
	"image_url":"",
	"address":"jl buntu",
	"city_id":"153"
}

### Delete Store
DELETE http://localhost:5000/api/store/cc57e8e1-ce13-45b8-ac87-a93ea8611294
Access-Token:

### Find Store
GET http://localhost:5000/api/store/find?page=1&limit=2&search=bu
Access-Token:

### Get Store
GET http://localhost:5000/api/store/e9c49a8d-f156-431a-9f65-e3012fb29f45
Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbmR5Iiwic3ViIjoic2FuZHlAZ21haWwuY29tIiwiZXhwIjoxNjk3NDQ1MTgyLCJqdGkiOiIzNzcyZDllYS04N2M0LTRlMDEtOGYxNC04NmIyYjViZTVmNjgifQ.eJyo4CXBJufC92Mmf6WFIXy38m4ua5QIuMhvoEDcydU

### Get Store Report 
GET http://localhost:5000/api/store/report/8bae8813-c361-4b1a-8c20-59f78010728e?startDate=2023-10-22&endDate=2023-10-30
Access-Token:

### Create Product
POST http://localhost:5000/api/product/create
Access-Token:

{
  "product_name":"Aqua",
	"description":"Contoh Deskripsi",
	"category":"Kebutuhan",
	"stock":"99",
	"price":"4000",
	"image_url":"",
	"weight_on_gram":1000
}

### Update Product
PUT http://localhost:5000/api/product/33f389da-3963-4087-b4de-6309928b710c
Access-Token:

{
  "product_name":"",
	"description":"",
	"category":"",
	"stock":"",
	"price":"",
	"image_url":"",
	"weight_on_gram":0
}

### Delete Product
DELETE http://localhost:5000/api/product/5aaa787d-02d3-4487-bc75-b543da26c897
Access-Token:

### Find Product
GET http://localhost:5000/api/product/find?search=a&page=1&limit=5
Access-Token:

### Get Product
GET http://localhost:5000/api/product/5aaa787d-02d3-4487-bc75-b543da26c897
Access-Token:

### Add Product
POST http://localhost:5000/api/cart/add/f65b5f57-620a-4316-b9c0-4b269d344b82?qty=2
Access-Token:

### Delete Cart
DELETE http://localhost:5000/api/cart/db1106eb-48be-49e4-9ebc-651331072944
Access-Token:

### Update Item Cart
PUT http://localhost:5000/api/cart/item/a042ded2-9ff5-4431-813b-63c7953cf1bc?qty=3
Access-Token:

### Delete Item Cart
DELETE http://localhost:5000/api/cart/item/a042ded2-9ff5-4431-813b-63c7953cf1bc
Access-Token:

### Get My Cart
GET http://localhost:5000/api/cart/get
Access-Token:

### Cek Ongkir
GET http://localhost:5000/api/transaction/ongkir/e39eecaa-828e-45b1-9447-56aae81a8fe7?expedition=tiki
Access-Token:

### Checkout
POST http://localhost:5000/api/transaction/checkout/e39eecaa-828e-45b1-9447-56aae81a8fe7?payment=bca
Access-Token:

{
	"origin_city":"Jakarta Barat",
	"destination_city":"Jakarta Selatan",
	"courier":"tiki",
	"weight_on_gram":"2000",
	"service":"ECO",
	"description":"Economy Service",
	"price":16000
}

### Callback Midtrans
POST http://localhost:5000/api/transaction/callback 

### Get Transaction By User Id
GET http://localhost:5000/api/transaction/user/4e9497c1-fb82-4301-94a8-7d0b4d6c4f53
Access-Token:

### Get Transaction By Store Id
GET http://localhost:5000/api/transaction/store/8bae8813-c361-4b1a-8c20-59f78010728e
Access-Token:

### Create Product Review
POST http://localhost:5000/api/review/create/190fce26-fd07-48df-9283-84759abbefae
Access-Token:

{
	"comment":"Product bagus dan murah"
}

### Get Product Review
GET http://localhost:5000/api/review/get/190fce26-fd07-48df-9283-84759abbefae?page=1&limit=10
Access-Token:

### Update Product Review
PUT http://localhost:5000/api/review/c18b0b9e-fcf4-4863-8f33-f361f95c24f1
Access-Token:

{
	"comment":"Product bagus dan murah banget"
}

### Delete Product Review
DELETE http://localhost:5000/api/review/c18b0b9e-fcf4-4863-8f33-f361f95c24f1
Access-Token: